// Catalogue. Prices are placeholder retail prices in EUR, excluding VAT.
window.FINISHES = {
  satin: { name: "Satin", pct: 0 },
  mirror: { name: "Mirror polish", pct: 0.05 },
  black: { name: "Matte black coat", pct: 0.1 },
  titanium: { name: "Black titanium coat", pct: 0.15 }
};

window.CATEGORIES = [
  { id: "cuticle-nippers", name: "Cuticle nippers", draw: { type: "nipper", jaw: 5 },
    blurb: "Box-joint nippers with a double spring, sharpened and tested on cuticle film before packing." },
  { id: "nail-nippers", name: "Nail nippers", draw: { type: "nipper", jaw: 12, heavy: true },
    blurb: "Heavier jaws for fingernails and thick toenails, with lap or barrel springs." },
  { id: "manicure-scissors", name: "Manicure scissors", draw: { type: "scissors", small: true },
    blurb: "Fine curved and straight scissors for cuticles and nails, hand-set at the screw." },
  { id: "pushers-files", name: "Pushers & files", draw: { type: "pusher" },
    blurb: "Double-ended pushers with a knurled grip and stainless files with a laser-cut surface." },
  { id: "tweezers", name: "Tweezers", draw: { type: "tweezers", tip: "slant" },
    blurb: "Hand-aligned tips that meet along their full edge. Slant, point, flat and lash." },
  { id: "barber", name: "Barber shears & razors", draw: { type: "scissors" },
    blurb: "Hair shears in 440C steel with convex edges, plus thinning, texturizing and razors." },
  { id: "grooming", name: "Pet grooming shears", draw: { type: "scissors", long: true, curved: true },
    blurb: "Long straight, curved and chunker shears for grooming salons." },
  { id: "sets", name: "Sets & cases", draw: { type: "set" },
    blurb: "Ready-to-sell kits in leather or zip cases. Popular for private label." }
];

window.PRODUCTS = [
  // Cuticle nippers
  { id: "cuticle-nipper-full-jaw", sku: "FN-C05", cat: "cuticle-nippers", name: "Cuticle nipper, full jaw 5 mm",
    price: 16.9, length: 105, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin", "mirror", "black"],
    draw: { type: "nipper", jaw: 5 }, best: true,
    summary: "The everyday salon nipper. A 5 mm jaw removes cuticle in fewer cuts.",
    details: ["Double spring with a smooth, even return", "Box joint, riveted and hand-adjusted", "Jaw tested on cuticle film before packing", "Supplied with a silicone tip cap"] },
  { id: "cuticle-nipper-half-jaw", sku: "FN-C03", cat: "cuticle-nippers", name: "Cuticle nipper, half jaw 3 mm",
    price: 16.9, length: 105, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin", "mirror", "black"],
    draw: { type: "nipper", jaw: 3 },
    summary: "A shorter jaw for more control around the side walls.",
    details: ["Double spring", "Box joint, riveted and hand-adjusted", "Jaw tested on cuticle film", "Silicone tip cap"] },
  { id: "cuticle-nipper-quarter-jaw", sku: "FN-C02", cat: "cuticle-nippers", name: "Cuticle nipper, quarter jaw 2 mm",
    price: 17.9, length: 100, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin", "mirror"],
    draw: { type: "nipper", jaw: 2 },
    summary: "Precision jaw for Russian and dry manicure techniques.",
    details: ["Fine tapered tips", "Double spring", "Hand-sharpened edges", "Silicone tip cap"] },
  { id: "cuticle-nipper-single-spring", sku: "FN-C07", cat: "cuticle-nippers", name: "Cuticle nipper, single spring 7 mm",
    price: 13.5, length: 110, steel: "AISI 410 stainless", finishes: ["satin", "black"],
    draw: { type: "nipper", jaw: 7, single: true },
    summary: "An affordable nipper for training kits and resale.",
    details: ["Single leaf spring", "Lap joint", "Good choice for student kits"] },

  // Nail nippers
  { id: "nail-nipper-straight", sku: "FN-N12", cat: "nail-nippers", name: "Nail nipper, straight 12 mm",
    price: 19.9, length: 120, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin", "mirror"],
    draw: { type: "nipper", jaw: 12, heavy: true }, best: true,
    summary: "Straight cutting edge for clean, square fingernail shaping.",
    details: ["Double spring", "Box joint", "Straight jaw, 12 mm"] },
  { id: "nail-nipper-barrel-spring", sku: "FN-N13", cat: "nail-nippers", name: "Nail nipper, curved, barrel spring",
    price: 22.5, length: 125, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin", "mirror", "black"],
    draw: { type: "nipper", jaw: 13, heavy: true, barrel: true },
    summary: "A curved jaw with a barrel spring for a softer, steadier action.",
    details: ["Barrel spring", "Box joint", "Curved jaw, 13 mm"] },
  { id: "toenail-nipper-thick", sku: "FN-N14", cat: "nail-nippers", name: "Toenail nipper, thick nail 14 mm",
    price: 24.9, length: 135, steel: "AISI 420 stainless, 52–54 HRC", finishes: ["satin"],
    draw: { type: "nipper", jaw: 14, heavy: true },
    summary: "Long handles and a strong jaw for thick toenails in pedicure work.",
    details: ["Double spring", "Heavy box joint", "Straight jaw, 14 mm", "For cosmetic pedicure use"] },

  // Manicure scissors
  { id: "cuticle-scissors-curved", sku: "FS-C09", cat: "manicure-scissors", name: "Cuticle scissors, curved 9 cm",
    price: 11.9, length: 90, steel: "AISI 420 stainless", finishes: ["satin", "mirror", "black"],
    draw: { type: "scissors", small: true, curved: true }, best: true,
    summary: "Thin curved blades that follow the cuticle line.",
    details: ["Fine curved blades", "Hand-set screw tension", "Arrow-point tips"] },
  { id: "nail-scissors-straight", sku: "FS-N09", cat: "manicure-scissors", name: "Nail scissors, straight 9 cm",
    price: 10.9, length: 90, steel: "AISI 420 stainless", finishes: ["satin", "mirror"],
    draw: { type: "scissors", small: true },
    summary: "Straight blades for trimming and shaping nails.",
    details: ["Straight blades", "Hand-set screw tension"] },
  { id: "combination-scissors", sku: "FS-X09", cat: "manicure-scissors", name: "Combination scissors, nail and cuticle",
    price: 12.5, length: 95, steel: "AISI 420 stainless", finishes: ["satin", "mirror"],
    draw: { type: "scissors", small: true, curved: true },
    summary: "One blade shaped for nails, one for cuticles. A good travel and retail item.",
    details: ["Dual-purpose blades", "Hand-set screw tension"] },

  // Pushers & files
  { id: "pusher-spoon-hatchet", sku: "FP-SH", cat: "pushers-files", name: "Cuticle pusher, spoon and hatchet",
    price: 6.9, length: 125, steel: "AISI 410 stainless", finishes: ["satin", "mirror", "black"],
    draw: { type: "pusher" }, best: true,
    summary: "A rounded spoon pushes back cuticle; the hatchet lifts it from the nail plate.",
    details: ["Knurled, non-slip grip", "Polished, rounded edges", "Autoclavable"] },
  { id: "pusher-spoon-pterygium", sku: "FP-SP", cat: "pushers-files", name: "Cuticle pusher, spoon and pterygium",
    price: 6.9, length: 125, steel: "AISI 410 stainless", finishes: ["satin", "mirror"],
    draw: { type: "pusher", pointed: true },
    summary: "A sharpened pterygium end for removing dead skin from the nail plate.",
    details: ["Knurled grip", "Sharpened pterygium end", "Autoclavable"] },
  { id: "nail-file-double", sku: "FF-15", cat: "pushers-files", name: "Stainless nail file, double-ended 15 cm",
    price: 5.9, length: 150, steel: "AISI 420 stainless", finishes: ["satin"],
    draw: { type: "file" },
    summary: "A laser-cut surface that doesn't wear flat like paper files.",
    details: ["Laser-cut filing surface", "Pointed cleaner tip", "Washable and autoclavable"] },

  // Tweezers
  { id: "tweezers-slant", sku: "FT-SL", cat: "tweezers", name: "Slant tweezers, hand-aligned",
    price: 9.9, length: 95, steel: "AISI 420 stainless", finishes: ["satin", "mirror", "black"],
    draw: { type: "tweezers", tip: "slant" }, best: true,
    summary: "Tips meet along their full edge, so fine hairs grip on the first try.",
    details: ["Hand-aligned tips", "Satin grip area", "Protective tip cap"] },
  { id: "tweezers-point", sku: "FT-PT", cat: "tweezers", name: "Point tweezers, fine",
    price: 9.9, length: 95, steel: "AISI 420 stainless", finishes: ["satin", "mirror"],
    draw: { type: "tweezers", tip: "point" },
    summary: "Needle-fine tips for ingrown and very short hairs.",
    details: ["Hand-aligned tips", "Protective tip cap"] },
  { id: "tweezers-lash", sku: "FT-LC", cat: "tweezers", name: "Lash tweezers, curved",
    price: 11.5, length: 115, steel: "AISI 420 stainless, anti-magnetic", finishes: ["satin", "titanium"],
    draw: { type: "tweezers", tip: "curve" },
    summary: "Curved tips for isolating and placing lash extensions.",
    details: ["Anti-magnetic steel", "Curved fine tips", "Tip cap"] },
  { id: "tweezers-flat", sku: "FT-FL", cat: "tweezers", name: "Flat-tip tweezers",
    price: 8.9, length: 95, steel: "AISI 420 stainless", finishes: ["satin", "mirror"],
    draw: { type: "tweezers", tip: "flat" },
    summary: "A broad grip for brows and general salon use.",
    details: ["Wide flat tips", "Protective tip cap"] },

  // Barber
  { id: "barber-shears-6-offset", sku: "FB-60", cat: "barber", name: "Barber shears 6.0\", offset handle",
    price: 64, length: 152, steel: "440C stainless, 58–60 HRC", finishes: ["mirror", "satin", "titanium"],
    draw: { type: "scissors" }, best: true,
    summary: "Convex-edge shears with an offset handle to keep the wrist relaxed.",
    details: ["Convex, hand-honed edge", "Adjustable tension screw", "Removable finger rest", "Leather pouch and oil included"] },
  { id: "barber-shears-7-straight", sku: "FB-70", cat: "barber", name: "Barber shears 7.0\", straight handle",
    price: 72, length: 178, steel: "440C stainless, 58–60 HRC", finishes: ["mirror", "satin", "titanium"],
    draw: { type: "scissors", long: true },
    summary: "Longer blades for scissor-over-comb and wide sections.",
    details: ["Convex edge", "Adjustable tension screw", "Leather pouch and oil included"] },
  { id: "thinning-shears-30", sku: "FB-T30", cat: "barber", name: "Thinning shears 6.0\", 30 teeth",
    price: 69, length: 152, steel: "440C stainless, 58–60 HRC", finishes: ["mirror", "satin", "titanium"],
    draw: { type: "scissors", teeth: 30 },
    summary: "Removes about 25–30% of hair per cut for blending.",
    details: ["30 V-teeth", "Adjustable tension screw", "Leather pouch included"] },
  { id: "texturizing-shears-14", sku: "FB-T14", cat: "barber", name: "Texturizing shears 6.0\", 14 teeth",
    price: 69, length: 152, steel: "440C stainless, 58–60 HRC", finishes: ["satin", "mirror", "titanium"],
    draw: { type: "scissors", teeth: 14 },
    summary: "Wide-spaced teeth for chunky texture and removing bulk.",
    details: ["14 wide teeth", "Adjustable tension screw", "Leather pouch included"] },
  { id: "barber-shears-left", sku: "FB-60L", cat: "barber", name: "Left-handed barber shears 6.0\"",
    price: 68, length: 152, steel: "440C stainless, 58–60 HRC", finishes: ["mirror", "satin"],
    draw: { type: "scissors", flip: true },
    summary: "Blades are reversed, not just the handle, so left-handed barbers see the cutting line.",
    details: ["True left-handed blade set", "Offset handle", "Leather pouch and oil included"] },
  { id: "shavette-razor", sku: "FR-SV", cat: "barber", name: "Shavette straight razor, folding",
    price: 18.5, length: 250, steel: "AISI 420 stainless", finishes: ["satin", "black"],
    draw: { type: "razor" },
    summary: "Takes standard half double-edge blades. For necklines, fades and beard lines.",
    details: ["Fits half DE blades", "Folding handle", "Blades not included"] },

  // Grooming
  { id: "grooming-shears-8-straight", sku: "FG-80", cat: "grooming", name: "Pet grooming shears 8.0\", straight",
    price: 48, length: 203, steel: "440C stainless", finishes: ["satin", "titanium"],
    draw: { type: "scissors", long: true }, best: true,
    summary: "Long blades for body work and finishing on medium and large breeds.",
    details: ["Convex edge", "Offset handle", "Adjustable tension"] },
  { id: "grooming-shears-7-curved", sku: "FG-70C", cat: "grooming", name: "Pet grooming shears 7.0\", curved",
    price: 52, length: 178, steel: "440C stainless", finishes: ["satin", "titanium"],
    draw: { type: "scissors", long: true, curved: true },
    summary: "A curved blade for rounded heads, feet and tails.",
    details: ["Curved convex blades", "Offset handle", "Adjustable tension"] },
  { id: "grooming-chunker-42", sku: "FG-CH42", cat: "grooming", name: "Chunker shears 7.5\", 42 teeth",
    price: 55, length: 190, steel: "440C stainless", finishes: ["satin", "titanium"],
    draw: { type: "scissors", long: true, teeth: 42 },
    summary: "Blends and softens lines without leaving scissor marks.",
    details: ["42 T-teeth", "Offset handle", "Adjustable tension"] },

  // Sets
  { id: "manicure-set-leather-7", sku: "FK-L7", cat: "sets", name: "Manicure set in leather case, 7 pieces",
    price: 39, length: 140, steel: "AISI 420 stainless", finishes: ["satin", "mirror"],
    draw: { type: "set" }, best: true,
    summary: "Cuticle nipper, nail clipper, cuticle scissors, slant tweezers, pusher, file and cleaner in a genuine leather case.",
    details: ["Genuine leather case, snap closure", "7 instruments", "Logo embossing available for private label"] },
  { id: "nail-tech-starter-kit", sku: "FK-S5", cat: "sets", name: "Nail technician starter kit, 5 pieces",
    price: 44, length: 180, steel: "AISI 420 stainless", finishes: ["satin"],
    draw: { type: "set", zip: true },
    summary: "Full-jaw nipper, curved cuticle scissors, spoon pusher, slant tweezers and file in a zip case. Built for nail academies.",
    details: ["Zip case with elastic holders", "5 salon-grade instruments", "Academy pricing from 20 kits"] }
];
